### ISSUE TITLE
Task List (Extra features)

### ISSUE THREAD

**Issue by yuvalbenkovski** [yuvalbenkovski/yelpcamp#1]
- [x] Add fuzzy searching for campgrounds
- [ ] Reseed database with reviews and ratings
- [ ] Add filtering feature for num of reviews [popularity], avg campground score, date of upload.
